---

- name: Add a new user
  user:
    name: "{{ ambith }}"
    comment: "{{ New user named ambith. }}"
    shell: /bin/bash
  tags:
    - add

- name: Give SSH access
  authorized_key:
    user: "{{ ambith }}"
    state: present
    key: "{{ lookup('file', '../sshkeys/{{ ambith }}/id_rsa.pub') }}"
  tags:
    - grant