---

- name: Revoke SSH access
  authorized_key:
    user: "{{ ambith }}"
    state: absent
    key: "{{ lookup('file', '../sshkeys/{{ ambith }}/id_rsa.pub') }}"
  tags:
    - revoke

- name: Remove user
  user:
    name: "{{ ambith }}"
    state: absent
    remove: yes
  tags:
    - remove